In [19]:
import numpy as np
#1. Seed the Range for reproducibility.
import random
y=np.random.seed(34)
print(y)

None


In [20]:
#2. Generate a random 6×6 integer matrix between 1–20.
m=np.random.randint(1,21,(6,6))
print(m)

[[ 2 11 10  5  4  6]
 [12 11 15 19  7  6]
 [ 1  6 20 20  9  9]
 [16 11 14  9 11 14]
 [ 5  3  6  3 11 12]
 [ 3 10  7  3  7 11]]


In [21]:
#3. Center the matrix by subtracting the column means (use broadcasting).
col_means=np.mean(m,axis=0)
c_matrix=m-col_means
print(c_matrix)

[[-4.5         2.33333333 -2.         -4.83333333 -4.16666667 -3.66666667]
 [ 5.5         2.33333333  3.          9.16666667 -1.16666667 -3.66666667]
 [-5.5        -2.66666667  8.         10.16666667  0.83333333 -0.66666667]
 [ 9.5         2.33333333  2.         -0.83333333  2.83333333  4.33333333]
 [-1.5        -5.66666667 -6.         -6.83333333  2.83333333  2.33333333]
 [-3.5         1.33333333 -5.         -6.83333333 -1.16666667  1.33333333]]


In [22]:
#4. Select all values in the centered matrix whose absolute value exceeds 1.5 (use Boolean indexing).
n=c_matrix>1.5
n=n.reshape(1,36)
print(n)

[[False  True False False False False  True  True  True  True False False
  False False  True  True False False  True  True  True False  True  True
  False False False False  True  True False False False False False False]]


In [23]:
#5. Compute and print: - Total sum, mean, std, min, max of the selected values (use aggregations).
a=np.sum(m)
print(a)
b=np.mean(m)
print(b)
c=np.std(m)
print(c)
d=np.min(m)
print(d)
e=np.max(m)
print(e)

329
9.13888888888889
4.950604776622852
1
20


In [ ]:
#6. Shuffle the rows of the original matrix (use shuffle) and display the first 3 rows. (# If you don't know about this then refer numpy documentation youll learn something new: 
np.random.shuffle(m)
print(m[:3])

[[ 1  6 20 20  9  9]
 [ 5  3  6  3 11 12]
 [ 3 10  7  3  7 11]]


: 